### ISSUE TITLE
Chinese error reporting bug in string

### ISSUE THREAD

**Issue by bbfpl** [amaui-org/amaui-zip#1]
The test found that as long as Chinese or Japanese appeared in the string, there would be parsing problems.
     
 const amauiZip = new AmauiZip(JSON.stringify({"_id":"page_2qewpv","name":"这是一句中文"}))
      // Encoded
      const response = amauiZip.encoded
      console.log(response)
      console.log(JSON.parse(AmauiZip.decode(response.value).value))

**Comment by lazar-eric** [comment]
Just saw this now for the first time, it was in Sep lol, I am not getting notifications for this.

Will have a look, it's a fresh library, haven't tested with characters outside ASCII (utf-8) I think. Thanks

**Comment by lazar-eric** [comment]
@bbfpl fixed, new version published now `1.0.11144`.

https://github.com/amaui-org/amaui-zip/commit/0f023e1e7d3315a393eb9d737340cee24f64dca9 

- Fixed in lz77 decoding text back to UTF-16
- Fixed in huffman-code last character having a bug with padded 0s for the } bracket in JSON

FYI, you don't have to stringify, serialization happens automatically. 

You can simply:
```javascript
new AmauiZip({"_id":"page_2qewpv","name":"这是一句中文"})
``` 

And it on decode, it will parse it back to the JSON object.  

Thanks <3
